campaign: ORCESTRA
campaign_id: ORCESTRA
platform: RV Meteor
platform_number: 1
location: Meteor
configs:
    main: config/main_Met.yaml  # name of this file
    level0: config/level0_Met.yml
    level1: config/level1_Vaisala.yaml
    level2: config/level2_Vaisala.yaml
