campaign: ORCESTRA
campaign_id: ORCESTRA
platform: BCO
platform_number: 1
location: Deebles Point
configs:
    main: config/main_BCO.yaml  # name of this file
    level0: config/level0_BCO.yml
    level1: config/level1_Vaisala.yaml
    level2: config/level2_Vaisala.yaml
